name: CutBox release update

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      release:
        required: true
        description: "CutBox version to release via Homebrew"

jobs:
  build:
    name: CutBox release update
    runs-on: macos-11
    env:
      RELEASE: ${{ github.event.inputs.release }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update CutBox homebrew
        run : |
          or_quit() { echo "$1" ; exit ${2:-1} }
          RELEASE="${{ env.RELEASE }}"
          echo "RELEASE.......: $RELEASE"
          BREW_VERSION=$(grep "VERSION:" README.md | awk '{ print $2 }')
          echo "LATEST ON BREW: $BREW_VERSION"
          if [[ "$BREW_VERSION" != "$RELEASE" ]]; then
            echo "Updating brew formula and cask to CutBox $RELEASE"
            echo "- Update readme"
            bin/update-readme "$RELEASE" || \
              or_quit "Update README failed"
            echo "- Update formula"
            bin/update-formula "$RELEASE" || \
              or_quit "Update Formula failed"
            echo "- Update cask"
            bin/update-cask "$RELEASE" || \
              or_quit "Update Cask failed"
            echo "- Test formula"
            bin/test-formula || \
              or_quit "Test Formula failed"
            echo "- Test cask"
            bin/test-cask || \
              or_quit "Test Cask failed"
            echo "Git commit / push"
            git status -s
            git add \
              README.md \
              Formula/cutbox.rb \
              Casks/cutbox.rb || \
                or_quit "git add failed"
            git commit -m "Update Homebrew: CutBox ${CUTBOX_VERSION}" || \
              or_quit "git commit failed"
            git tag "${CUTBOX_VERSION}" || \
              or_quit "git tag failed"
            git push --follow-tags || \
              or_quit "git push failed"
            echo "Released CutBox ${CUTBOX_VERSION} via homebrew"
          else
            echo "Cannot upgrade from: $BREW_VERSION -> $RELEASE"
          fi
