name: CutBox release update

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      release:
        required: true
        description: "CutBox version to release via Homebrew"

jobs:
  build:
    name: CutBox release update
    runs-on: macos-11
    env:
      RELEASE: ${{ github.event.inputs.release }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update CutBox homebrew
        run : |
          echo "RELEASE.......: $RELEASE"
          BREW_VERSION=$(grep "VERSION:" README.md | awk '{ print $2 }')
          echo "LATEST ON BREW: $BREW_VERSION"
          if [[ "$BREW_VERSION" != "$RELEASE" ]]; then
            echo "Updating brew formula and cask to CutBox $RELEASE"
          else
            echo "Already released $RELEASE"
            exit 1
          fi
      - name: Update readme
        run: |
          bin/update-readme "$RELEASE"
      - name: Update formula
        run: |
          bin/update-formula "$RELEASE"
      - name: Update cask
        run: |
          bin/update-cask "$RELEASE"
      - name: Test formula
        run: |
          bin/test-formula
      - name: Test cask
        run: |
          bin/test-cask
      - name: Git add
        run: |
          git status -s
          git add \
            README.md \
            Formula/cutbox.rb \
            Casks/cutbox.rb
      - name: Git commit
        run: |
          git commit -m "Update Homebrew: CutBox ${RELEASE}"
      - name: Git tag
        run: |          
          git tag "${RELEASE}"
      - name: Git push
        run: |
          git push
          git push --tags
